services:
  db:
    image: "postgres:latest"
    container_name: "mittel_auth_db"
    restart: "always"
    ports:
      - "5432:5432"
    env_file:
      - "db.env"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
