services:
  auth:
    build: "."
    container_name: "mittel_users_api"
    ports:
      - "4000:4000"
    env_file:
      - ".env"
    deploy:
      restart_policy:
        condition: "on-failure"
        delay: "5s"
        max_attempts: 3
    depends_on:
      - "db"
  db:
    image: "postgres:latest"
    container_name: "mittel_users_db"
    restart: "always"
    ports:
      - "5432:5432"
    env_file:
      - "db.env"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
